package com.complimentdamian;

public class Compliments {

  public static final String c1 = "I do like your brain a lot";
  public static final String c2 = "Your critical thinking is bewitching";
  public static final String c3 = "It's a pleasure to lie on your chest. And shoulders";
  public static final String c4 = "Your puppy is the cutest. Just like you";
  public static final String c5 = "I love your sense of explore and passion to learn something new";
  public static final String c6 = "I love your strong arms, they make me feel amazing when you hug me from behind";
  public static final String c7 = "I feel so peaceful when sleeping next to you";
  public static final String c8 = "I do love your style. When your wear shirts, it's just oh my god";
  public static final String c9 = "I love your playfulness. It resonates with mine so well";
  public static final String c10 = "Your craziness appeals to me a lot";
  public static final String c11 = "You have such a kind heart, I could clearly see it the way you treat animals. And me when I'm sick";
  public static final String c12 = "It's so easy for me to be myself with you. Thank you for being you";
  public static final String c13 = "It's so nice to see your drive and passion to what you do, I was fascinated by what you taught me about lighting and design";
  public static final String c14 = "Your ambitions are beautiful";
  public static final String c15 = "I love your gentleman'ish gestures. They make it so easy for me just to be a woman with you";
  public static final String c16 = "You are very, very, very cute (in the sense I mean it)";
  public static final String c17 = "I love the way you give me compliments. They are always well-thought and special. Never generic";
  public static final String c18 = "I love to be lying on your shoulder when listening to songs from Twin Peaks in your car";
  public static final String c19 = "You are so handsome, it's irresistible";
  public static final String c20 = "Your taste is amazing, so subtle and exquisite. I loved all the songs you shared with me";
  public static final String c21= "I love your sense of aesthetics";
  public static final String c22= "I love how you surround yourself with special meanings, like those pictures around your house which have a story behind them";
  public static final String c23= "Your creativity is mind-blowing, it ignites my internal fire a lot";
  public static final String c24= "I love discussing and implementing ideas with you, even when it's something silly";
  public static final String c25= "You make me laugh a lot, it's always so much fun to spend time with you";
  public static final String c26= "I started to smile a lot more since I met you, thank you";
  public static final String c27= "I love your dedication and enthusiasm, they are beautiful";
  public static final String c28= "You are so damn sexy";
  public static final String c29= "I love that you're able to see so many things about me which others fail to see. This matters a lot to me";
  public static final String c30= "Your sense of adventure is contagious";
  public static final String c31= "You somehow manage to keep me interested non-stop, I enjoy learning something new from you";
  public static final String c32= "I did not realise I could have so much fun at a train station date! It's fun to spend time with you even in silly places at the most inappropriate moments";
  public static final String c33= "I love your spontaneous creativity, like with those lamps with an in-built microphone. It was such a beautiful idea";
  public static final String c34= "I like when you call me a good girl";
  public static final String c35= "Your confidence is super attractive, especially when you say 'end of story'";
  public static final String c36= "You leave such lovely marks on my bum, love them!";
  public static final String c37= "I appreciate that you don't judge all of my crazy ideas";
  public static final String c38= "Your thoughts are so expressive, it makes it easy to communicate with you";
  public static final String c39= "You are so kind to me";
  public static final String c40= "I think the crown suits you ;)";
  public static final String c41= "It feels nice to be your Kitty";
  public static final String c42= "Distracting you from driving is my absolute pleasure";
  public static final String c43 = "You are so charming";
  public static final String c44 = "I feel so comfortable around you, like at home";
  public static final String c45 = "Your house is so artistic, it's nice to see art at every corner of it";
  public static final String c46 = "You are so sweet";
  public static final String c47 = "I like you a lot";
  public static final String c48 = "You somehow manage to turn me on within a fraction of a second, this is unreal";
  public static final String c49 = "You make me fully embrace my femininity, I really missed this feeling";
  public static final String c50 = "I appreciate the softness you treat me with, this lets me relax after being strong in every other sphere of my life";
  public static final String c51 = "Your mind is just as beautiful as your face";
  public static final String c52 = "You are very special";
  public static final String c53 = "Twoje spojrzenie jest magiczne";
  public static final String c54 = "Jesteś niezwykle kreatywny i zdolny";
  public static final String c55 = "Twoje serce jest tak wielkie, jak twoja dobroć";

}
